services:
  react-app:
    image: ghcr.io/bluenyang/my-react-app:latest
    container_name: react-app
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.react-app.rule=Host(`bluenyang.croffledev.kr`)'
      - 'traefik.http.routers.react-app.entrypoints=websecure'
      - 'traefik.http.services.react-app.loadbalancer.server.port=80'
